In [28]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
data = pd.read_csv('final_data_movies.csv', index_col=0)
mine = pd.read_csv('final_my_movies.csv', index_col=0)

In [20]:
data.head()

,movieId,title,genres,release_date,vote_average,vote_count,keywords
0.0,862,Toy Story,"Animation, Comedy, Family",1995,7.5,5400.0,"jealousy, toy, boy, friendship, friends"
1.0,8844,Jumanji,"Adventure, Fantasy, Family",1995,7.0,2400.0,"board game, disappearance, ""based on childrens..."
2.0,15602,Grumpier Old Men,"Romance, Comedy",1995,6.5,100.0,"fishing, best friend, duringcreditsstinger, ol..."
3.0,31357,Waiting to Exhale,"Comedy, Drama, Romance",1995,6.0,0.0,"based on novel, interracial relationship, sing..."
4.0,11862,Father of the Bride Part II,Comedy,1995,5.5,200.0,"baby, midlife crisis, confidence, aging, daughter"

In [10]:
mine.head()

,Watched,Day,movieId,title,genres,release_date,vote_average,vote_count,keywords
0,with family,monday,4258,Scary Movie 5,Comedy,2013,4.5,800,"sequel, parody, spoof, aftercreditsstinger, du..."
1,with family,monday,71880,Jack and Jill,Comedy,2011,4.0,600,duringcreditsstinger
2,with family,saturday,188207,The Legend of Hercules,"Action, Adventure",2014,4.5,500,"mythology, zeus, ancient greece, demigod, city..."
3,with family,tuesday,314,Catwoman,"Action, Crime",2004,4.0,800,"white russian, sex, dc comics, beauty, sexism"
4,with family,monday,263472,Knock Knock,"Drama, Thriller",2015,5.0,900,"female nudity, sex, disc jockey, infidelity, rain"

In [23]:
data = data.set_index('movieId')
mine = mine.set_index('movieId')

In [13]:
mine.head()

,Watched,Day,title,genres,release_date,vote_average,vote_count,keywords
movieId,,,,,,,,
4258,with family,monday,Scary Movie 5,Comedy,2013,4.5,800,"sequel, parody, spoof, aftercreditsstinger, du..."
71880,with family,monday,Jack and Jill,Comedy,2011,4.0,600,duringcreditsstinger
188207,with family,saturday,The Legend of Hercules,"Action, Adventure",2014,4.5,500,"mythology, zeus, ancient greece, demigod, city..."
314,with family,tuesday,Catwoman,"Action, Crime",2004,4.0,800,"white russian, sex, dc comics, beauty, sexism"
263472,with family,monday,Knock Knock,"Drama, Thriller",2015,5.0,900,"female nudity, sex, disc jockey, infidelity, rain"

In [21]:
data.head()

,movieId,title,genres,release_date,vote_average,vote_count,keywords
0.0,862,Toy Story,"Animation, Comedy, Family",1995,7.5,5400.0,"jealousy, toy, boy, friendship, friends"
1.0,8844,Jumanji,"Adventure, Fantasy, Family",1995,7.0,2400.0,"board game, disappearance, ""based on childrens..."
2.0,15602,Grumpier Old Men,"Romance, Comedy",1995,6.5,100.0,"fishing, best friend, duringcreditsstinger, ol..."
3.0,31357,Waiting to Exhale,"Comedy, Drama, Romance",1995,6.0,0.0,"based on novel, interracial relationship, sing..."
4.0,11862,Father of the Bride Part II,Comedy,1995,5.5,200.0,"baby, midlife crisis, confidence, aging, daughter"

In [15]:
family = mine[mine['Watched'] == 'with family']
family.drop(['Watched', 'Day'], axis=1, inplace=True)

alone = mine[mine['Watched'] == 'Alone']
alone.drop(['Watched', 'Day'], axis=1, inplace=True)

gf = mine[mine['Watched'] == 'with gf']
gf.drop(['Watched', 'Day'], axis=1, inplace=True)

workdays = mine[(mine['Watched'] != 'sunday') & (mine['Day'] != 'saturday')]
workdays.drop(['Watched', 'Day'], axis=1, inplace=True)

weekend = mine[(mine['Day'] == 'sunday') | (mine['Day'] == 'saturday')]
weekend.drop(['Watched', 'Day'], axis=1, inplace=True)

/home/erol/jupyter/jupyter/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [18]:
weekend.drop(['title'], axis=1, inplace=True)
workdays.drop(['title'], axis=1, inplace=True)
alone.drop(['title'], axis=1, inplace=True)
gf.drop(['title'], axis=1, inplace=True)
family.drop(['title'], axis=1, inplace=True)

In [24]:
family = family.join(pd.get_dummies(family.keywords))
family.drop('keywords', axis=1, inplace=True)
family = family.join(pd.get_dummies(family.genres))
family.drop('genres', axis=1, inplace=True)

alone = alone.join(pd.get_dummies(alone.keywords))
alone.drop('keywords', axis=1, inplace=True)
alone = alone.join(pd.get_dummies(alone.genres))
alone.drop('genres', axis=1, inplace=True)

gf = gf.join(pd.get_dummies(gf.keywords))
gf.drop('keywords', axis=1, inplace=True)
gf = gf.join(pd.get_dummies(gf.genres))
gf.drop('genres', axis=1, inplace=True)

workdays = workdays.join(pd.get_dummies(workdays.keywords))
workdays.drop('keywords', axis=1, inplace=True)
workdays = workdays.join(pd.get_dummies(workdays.genres))
workdays.drop('genres', axis=1, inplace=True)

weekend = weekend.join(pd.get_dummies(weekend.keywords))
weekend.drop('keywords', axis=1, inplace=True)
weekend = weekend.join(pd.get_dummies(weekend.genres))
weekend.drop('genres', axis=1, inplace=True)

In [63]:
alone_weekend = pd.concat([alone, weekend], axis=1)
alone_workdays = pd.concat([alone, workdays], axis=1)

gf_weekend = pd.concat([gf, weekend], axis=1)
gf_workdays = pd.concat([gf, workdays], axis=1)

family_weekend = pd.concat([family, weekend], axis=1)
family_workdays = pd.concat([family, workdays], axis=1)

In [66]:
alone_weekend = alone_weekend.dropna()
alone_workdays = alone_workdays.dropna()

gf_weekend = gf_weekend.dropna()
gf_workdays = gf_workdays.dropna()

family_weekend = family_weekend.dropna()
family_workdays = family_workdays.dropna()

In [68]:
alone_weekend = alone_weekend.loc[:,~alone_weekend.columns.duplicated()]
alone_weekend = alone_weekend[alone_weekend['vote_average'] > 5.0]

alone_workdays = alone_workdays.loc[:,~alone_workdays.columns.duplicated()]
alone_workdays = alone_workdays[alone_workdays['vote_average'] > 5.0]

gf_weekend = gf_weekend.loc[:,~gf_weekend.columns.duplicated()]
gf_weekend = gf_weekend[gf_weekend['vote_average'] > 5.0]

gf_workdays = gf_workdays.loc[:,~gf_workdays.columns.duplicated()]
gf_workdays = gf_workdays[gf_workdays['vote_average'] > 5.0]

family_weekend = family_weekend.loc[:,~family_weekend.columns.duplicated()]
family_weekend = family_weekend[family_weekend['vote_average'] > 5.0]

family_workdays = family_workdays.loc[:,~family_workdays.columns.duplicated()]
family_workdays = family_workdays[family_workdays['vote_average'] > 5.0]

In [175]:
my_ratings = pd.read_csv('myWatchedMovies2.csv', index_col=0)

In [176]:
my_ratings = my_ratings[['Watched', 'Day', 'Rating', 'movieId', 'title']]

In [193]:
def get_recomm_movies(x):
    Filtering_cosim = cosine_similarity(x,x)
    best_movies = []
    recommendations = []
    
    for ind, i in enumerate(x.index):
        if my_ratings.loc[i].Rating >= 3.0:
            best_movies.append(ind)
    
    for i in best_movies:
        most_sim_movies = sorted(list(enumerate(Filtering_cosim[i])), key=lambda x: x[1], reverse=True)
        most_sim_movies = most_sim_movies[1:11]
        sim_movies = [x[0] for x in most_sim_movies]
        for i in sim_movies:
            if (data.iloc[i].title) in recommendations:
                continue
            else:                
                recommendations.append(data.iloc[i].title)
        
    return recommendations

In [198]:
get_recomm_movies(gf_weekend)

['Nixon',
 'Powder',
 'Tom and Huck',
 'Assassins',
 'Sense and Sensibility',
 'Dracula: Dead and Loving It',
 'Persuasion',
 'Casino',
 'Leaving Las Vegas',
 'Copycat',
 'Heat',
 'Now and Then',
 'Sudden Death',
 'Sabrina',
 'Father of the Bride Part II',
 'Grumpier Old Men',
 'Waiting to Exhale',
 'Get Shorty',
 'Ace Ventura: When Nature Calls',
 'Cutthroat Island',
 'Four Rooms',
 'Money Train',
 'GoldenEye',
 'Jumanji',
 'Toy Story',
 'Othello',
 'The American President',
 'Balto']